-- Migration: RLS owner-only para operaciones_inmobiliarias — NO-OP DOCUMENTADO.
--
-- ⚠️ ESTA MIGRACIÓN NO EJECUTA NINGÚN DDL A PROPÓSITO. Es un no-op puro (solo
--    comentarios). Se conserva por TRAZABILIDAD del razonamiento de seguridad, no
--    para ejecutarse. Aplicarla no debe crear ni modificar nada.
--
-- ─────────────────────────────────────────────────────────────────────────────
-- POR QUÉ NO HACE NADA
--
-- Producción (proyecto Supabase `zrstaskwqwuxgelcrwxx`) FUE VERIFICADA en vivo
-- (consultas de solo lectura, 2026-07-03) y `operaciones_inmobiliarias` YA tiene la
-- protección owner-only completa:
--
--   · RLS habilitada  → pg_class.relrowsecurity = true.
--   · Policies owner-only ya existentes, TODAS con `auth.uid() = user_id`:
--       - "Users can manage their own operaciones"  (ALL   · using + with_check)
--       - "operaciones_select"                      (SELECT · using)
--       - "operaciones_insert"                      (INSERT · with_check)
--       - "operaciones_update"                      (UPDATE · using + with_check)
--       - "operaciones_delete"                      (DELETE · using)
--   · Índice sobre user_id ya existente: `operaciones_inmobiliarias_user_id_idx`.
--   · Grants: `authenticated` con SELECT/INSERT/UPDATE/DELETE gateados fila a fila
--     por las policies RLS. `anon` SIN SELECT/DML (verificado: pull/insert anónimos
--     → 401; solo conserva REFERENCES/TRIGGER/TRUNCATE, sin acceso a datos).
--
-- Es decir: el aislamiento entre usuarios autenticados YA está garantizado en la BD.
--
-- ─────────────────────────────────────────────────────────────────────────────
-- POR QUÉ NO SE CREAN POLICIES AQUÍ (evitar duplicados)
--
-- La versión anterior de este archivo creaba 4 policies con nombres NUEVOS
-- ("operaciones_inmobiliarias: select own", etc.). Como las policies vivas usan
-- OTROS nombres (los listados arriba), esos `CREATE POLICY ... IF NOT EXISTS` por
-- nombre NO detectarían las existentes y añadirían 4 policies DUPLICADAS
-- (misma condición `auth.uid() = user_id`, distinto nombre). No aportarían
-- seguridad y ensuciarían la tabla. Por eso esta migración queda INTENCIONADAMENTE
-- SIN DDL: nada de CREATE/ALTER/DROP POLICY, nada de ALTER TABLE, nada de GRANT,
-- nada de índices. No toca datos.
--
-- ─────────────────────────────────────────────────────────────────────────────
-- INVERSORES (frontera de datos)
--
-- Los inversores NO acceden a `operaciones_inmobiliarias`. Su acceso va
-- EXCLUSIVAMENTE por `investment_shares.payload`, un snapshot ya filtrado por
-- visibilidad que publica el propietario (ver 20260702_investment_shares.sql y
-- src/lib/shares.ts → buildInvestorSnapshot). La RLS de `operaciones_inmobiliarias`
-- NO se abre a inversores en ningún caso.
--
-- ─────────────────────────────────────────────────────────────────────────────
-- SI EN EL FUTURO SE QUISIERA VERSIONAR REALMENTE (fuera de alcance)
--
-- Solo tendría sentido en un entorno NUEVO donde estas policies NO existan. En ese
-- caso, replicar EXACTAMENTE los nombres y condiciones vivos (arriba) — no nombres
-- nuevos — para que siga siendo idempotente por nombre. Antes de ejecutar nada,
-- correr las consultas de PASO 1 (solo lectura) contra el proyecto destino:
--
--   SELECT relname, relrowsecurity FROM pg_class
--     WHERE oid = 'public.operaciones_inmobiliarias'::regclass;
--   SELECT policyname, cmd, qual, with_check FROM pg_policies
--     WHERE schemaname='public' AND tablename='operaciones_inmobiliarias';
--   SELECT grantee, privilege_type FROM information_schema.role_table_grants
--     WHERE table_schema='public' AND table_name='operaciones_inmobiliarias'
--     ORDER BY grantee, privilege_type;
--
-- NOTA: otras tablas sin RLS versionada en el repo (app_settings, ai_meta_drafts,
-- profile_settings) quedan FUERA del alcance de esta tarea y no se tocan aquí.
--
-- FIN — no-op intencional. No hay sentencias ejecutables por debajo de esta línea.
